export type skillModule = {
  title: string;
  skillList: string[];
  descList: string[];
};

export const modules: skillModule[] = [
  {
    title: 'Front-End',
    skillList: [
      'Next.js',
      'TypeScript',
      'JavaScript',
      'React',
      'React Hooks',
      'Redux',
      'Material-UI',
      'Styled Components',
      'jQuery',
      'HTML',
      'CSS',
    ],
    descList: [
      'React framework that enables server-side rendering, static site generation, and simplified routing for building fast, scalable web applications.',
      'A statically typed superset of JavaScript that adds optional type checking and modern features to help developers write safer, more maintainable code.',
      "JavaScript is the first programming language learned and where I wrote my first 'Hello World'",
      'React is the modern framework I prefer to use when building applications. This site was built with React!',
      'React Hooks uses only functional components, which streamlines React applications and makes them more understandable and readable',
      'Predictable state container for JavaScript applications that manages state through a single store and unidirectional data flow using actions and reducers.',
      'Material-UI is a package with pre-built and thoroughly tested user interface components, that make web development faster and easier',
      'A modern styling package that allows developers to build fully customized CSS directly into React components',
      'The very first application I built used only jQuery, vanilla JS, and CSS',
      'This is the foundation of all modern web applications',
      'I style pixel-perfect user interfaces with a deep knowledge of CSS',
    ],
  },
  {
    title: 'Back-End',
    skillList: [
      'Python',
      'Flask',
      'Node',
      'Express',
      'MongoDB',
      'PostgreSQL',
      'MySQL',
      'Apache Cassandra',
    ],
    descList: [
      'A high-level, object-oriented programming language known for its readability, simplicity, and wide range of applications from web development to data science.',
      'A lightweight Python web framework that provides simple tools and flexibility for building web applications and APIs.',
      'A JavaScript runtime for building fast, server-side applications.',
      'Fast, unopinionated web framework for Node.js used to build APIs and web applications.',
      'An exceptional NoSQL database that is flexible and easy to use',
      'Powerful, open-source relational database system known for its reliability, extensibility, and SQL compliance.',
      'Widely used relational database management system known for its speed, reliability, and ease of use',
      'Cassandra is a scalable, distributed NoSQL database built for high availability and large data volumes.',
    ],
  },
  {
    title: 'Data & AI',
    skillList: [
      'ChromaDB',
      'LangChain',
      'LiteLLM',
      'Ollama',
      'OpenWebUi',
      'Cloudflare',
      'gpt-4.1',
      'Mistral',
      'nomic-embed-text',
      'IBM watsonx.ai',
      'IBM watsonx.governance',
      'IBM Knowledge Catalog',
      'IBM Watson Machine Learning',
    ],
    descList: [
      'Vector database designed to store, index, and search high dimensional embeddings for applications like similarity search and machine learning.',
      'Framework that helps developers build applications by connecting large language models with external data sources and tools through modular components.',
      'Lightweight, open-source platform for managing, serving, and deploying large language models locally with efficient resource use.',
      'A tool that enables running and managing large language models locally for fast, private, and customizable AI-powered applications.',
      'This web-based interface provides easy access and management of local large language models through a user friendly dashboard.',
      'Global network service that improves website performance and security by providing content delivery, DDoS protection, and DNS management.',
      'Advanced large language model that generates human-like text and understands complex language tasks with high accuracy and contextual awareness.',
      'High performance, open-source large language model optimized for efficiency and accuracy in natural language understanding and generation tasks.',
      'Embedding model designed to convert text into high quality vector representations for improved semantic search and machine learning applications.',
      'Enterprise grade platform that integrates generative AI and traditional machine learning, providing tools for building, fine-tuning, and deploying AI models across hybrid cloud environments.',
      'Comprehensive toolkit that enables organizations to govern and monitor AI models throughout their lifecycle, ensuring compliance with global regulations, mitigating risks such as bias and drift, and enhancing transparency and accountability in AI deployments.',
      'Intelligent data catalog that automates data discovery, quality management, and governance, enabling organizations to curate, understand, and securely access data assets across cloud and on-premises environments.',
      'Cloud based service that enables building, training, and deploying machine learning models at scale with automated tools and integrated AI lifecycle management.',
    ],
  },
  {
    title: 'Tools',
    skillList: [
      'IBM watsonx Code Assistant',
      'IBM watsonx Discovery',
      'IBM Watson Orchestrate',
      'IBM watsonx Assistant',
      'IBM Watson Assistant',
      'IBM Watson Discovery',
      'IBM Watson Speech to Text',
      'IBM Watson Text to Speech',
      'Tekton',
      'Argo CD',
      'TravisCI',
      'Swagger',
      'Docker',
      'Nginx',
      'Git/Github',
      'K6',
      'Loader.io',
      'Webpack',
      'Babel',
      'Jest/Enzyme',
      'Mocha/Chai',
      'Eslint',
      'Trello',
      'Puppeteer',
    ],
    descList: [
      'AI-powered coding assistant that helps developers write, debug, and optimize code more efficiently through intelligent suggestions and automation.',
      'An AI-driven search and analytics platform that indexes and queries large volumes of structured and unstructured data to uncover insights and support informed decision-making.',
      'A cloud-native automation platform that uses AI to streamline and coordinate business workflows by integrating tasks, data, and applications across multiple systems to improve efficiency and productivity.',
      'IBM watsonx Assistant is an AI-powered chatbot platform for building conversational interfaces.',
      'This Virtual Assistant uses artificial intelligence that understands customers in context to provide fast, consistent, and accurate answers across any application, device, or channel.',
      'An award-winning AI-powered intelligent search and text-analytics platform that eliminates data silos and retrieves information buried inside enterprise data.',
      'I used this technology in combination with a Virtual Assistant to enable fast and accurate speech transcription',
      'An API cloud service that enables you to convert written text into natural-sounding audio in a variety of languages and voices within an existing application or within Watson Assistant.',
      'This powerful and flexible CI/CD pipeline tool integrates seamlessly with Openshift. It provides Kubernetes-style resources for declaring CI/CD concepts',
      'A declarative, GitOps continuous delivery tool for Kubernetes that allows for easy, automated deployment and mananagment of applicaitons in controlled environments',
      "It's a hosted, distributed continuous integration service used to build and test software projects hosted on GitHub.",
      'An amazing tool that helps accelerate the design, building, and documentation of API services',
      'My preferred method of containerization for deployment',
      'I have experience implementing Nginx as a load balancer to scale a service for high web traffic',
      'My favorite version control system that I use for most of my applications',
      'An open-source load testing tool that makes performance testing easier',
      'A cloud based load and scalability testing service',
      'JavaScript module bundler that compiles, transforms, and optimizes application assets like scripts, styles, and images into efficient bundles for deployment.',
      'A JavaScript compiler that works well with both JavaScript and TypeScript',
      'A simple yet powerful combo for testing React components',
      'Mocha is a JavaScript testing utility used in combination with Chai an assertion library for testing',
      'Eslint helps programmers follow best practices by identifying problematic code during the development process',
      'Trello is an easy to use collaboration tool that lets users organize projects on boards. This is very helpful in Kanban style workflow management',
      'Puppeteer is a Node.js library that provides high-level API control of a headless Chrome browser',
    ],
  },
  {
    title: 'Cloud, Scaling & Methodology',
    skillList: [
      'Red Hat Openshift',
      'Kubernetes',
      'Ansible',
      'Terraform',
      'CI/CD',
      'REST',
      'Agile',
      'TDD',
      'MVC',
    ],
    descList: [
      'An enterprise-grade container application platform built on Kubernetes that streamlines development, deployment, and management of applications with integrated tools and enhanced security features.',
      'An open-source system for automating the deployment, scaling, and management of containerized applications across clusters of servers.',
      'Open-source automation tool that simplifies configuration management, application deployment, and task automation using simple, human-readable playbooks.',
      'Infrastructure-as-code tool that enables users to define, provision, and manage cloud and on-premises resources through declarative configuration files.',
      'CI/CD is a development practice that automates code integration, testing, and deployment to accelerate and streamline software delivery.',
      'An architectural style for web services that uses standard HTTP methods to access and manipulate resources through stateless, client-server interactions.',
      'I have experience with Agile practices including test-driven development, executing sprints, pair programing, and cross-team coordination',
      'A development practice where tests are written before code to guide design and ensure functionality through continuous testing.',
      'Model-View-Controller design pattern reinforces separation of concerns and good programming practices',
    ],
  },
];
